from .TelemetryData import TelemetryData
def create_data_object(unparsed_data:tuple)->TelemetryData:
    parsed_data = TelemetryData(unparsed_data[0],
                            unparsed_data[1],
                            unparsed_data[2],
                            unparsed_data[3],
                            unparsed_data[4],
                            unparsed_data[5],
                            unparsed_data[6],
                            unparsed_data[7],
                            unparsed_data[8],
                            unparsed_data[9],
                            unparsed_data[10],
                            unparsed_data[11],
                            unparsed_data[12],
                            unparsed_data[13],
                            unparsed_data[14],
                            unparsed_data[15],
                            unparsed_data[16],
                            unparsed_data[17],
                            unparsed_data[18],
                            unparsed_data[19],
                            unparsed_data[20],
                            unparsed_data[21],
                            unparsed_data[22],
                            unparsed_data[23],
                            unparsed_data[24],
                            unparsed_data[25],
                            unparsed_data[26],
                            unparsed_data[27],
                            unparsed_data[28],
                            unparsed_data[29],
                            unparsed_data[30],
                            unparsed_data[31],
                            unparsed_data[32],
                            unparsed_data[33],
                            unparsed_data[34],
                            unparsed_data[35],
                            unparsed_data[36],
                            unparsed_data[37],
                            unparsed_data[38]
                            )
    return parsed_data
